/**
 * fetch-thread-study.ts — 競合スレッド全文の追加取得スクリプト。
 *
 * 注意:
 * - このスクリプトは twitterapi.io へ外部 API call を行うため、Codex は実行しない。
 * - 人間が TWITTERAPI_IO_KEY を設定して実行する。
 *
 * 実行:
 *   cd apps/x-account-system
 *   TWITTERAPI_IO_KEY=... npx tsx scripts/fetch-thread-study.ts
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { getThread, searchTweets, type Tweet } from "../lib/ingest/twitterapi-client.js";

const HANDLES = [
  "MakeAI_CEO",
  "ClaudeCode_love",
  "ClaudeCode_UT",
  "nobel_824",
  "Gencoin8",
  "obsidianstudio9",
] as const;

const SINCE = "2026-04-29";
const MIN_FAVES = 50;
const MAX_ROOTS_PER_HANDLE = 12;
const OUT_DIR = path.resolve(
  process.cwd(),
  "../../raw/publishing/research/2026-06-13-viral-and-thread-study",
);

interface ThreadRecord {
  handle: string;
  root: Tweet;
  thread: Tweet[];
}

function apiKey(): string {
  const key = process.env.TWITTERAPI_IO_KEY;
  if (!key) {
    throw new Error("TWITTERAPI_IO_KEY is required");
  }
  return key;
}

function rootCandidates(tweets: Tweet[]): Tweet[] {
  const seen = new Set<string>();
  const roots: Tweet[] = [];
  for (const tweet of tweets) {
    const rootId = tweet.conversationId ?? tweet.id;
    if (seen.has(rootId)) continue;
    seen.add(rootId);
    roots.push(tweet);
  }
  return roots.slice(0, MAX_ROOTS_PER_HANDLE);
}

async function fetchHandle(handle: string, key: string): Promise<ThreadRecord[]> {
  const query = `from:${handle} since:${SINCE} min_faves:${MIN_FAVES} -is:retweet`;
  const tweets = await searchTweets(query, "Top", key);
  const roots = rootCandidates(tweets);
  const records: ThreadRecord[] = [];

  for (const root of roots) {
    const rootId = root.conversationId ?? root.id;
    const thread = await getThread(rootId, key);
    const ownThread = thread.filter((t) => t.author.userName === handle);
    records.push({ handle, root, thread: ownThread.length ? ownThread : thread });
  }

  return records;
}

async function main(): Promise<void> {
  const key = apiKey();
  await mkdir(OUT_DIR, { recursive: true });

  const metadata = {
    session_date: new Date().toISOString(),
    source: "twitterapi.io",
    note: "Full thread body study for 2026-06-13 viral writing and thread research. Generated by human-run script.",
    date_range: { since: SINCE },
    handles: HANDLES,
    min_faves: MIN_FAVES,
    max_roots_per_handle: MAX_ROOTS_PER_HANDLE,
    queries: HANDLES.map((handle) => ({
      handle,
      query: `from:${handle} since:${SINCE} min_faves:${MIN_FAVES} -is:retweet`,
      queryType: "Top",
    })),
  };

  await writeFile(path.join(OUT_DIR, "metadata.json"), JSON.stringify(metadata, null, 2));

  for (const handle of HANDLES) {
    const records = await fetchHandle(handle, key);
    await writeFile(
      path.join(OUT_DIR, `${handle}.threads.json`),
      JSON.stringify(records, null, 2),
    );
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
