/**
 * scripts/render-ma-agents.test.ts
 * planRender が「environment.yaml + 各 agent の .agent.yaml/.system.md」を正しく算出することを
 * 純粋に検証する（ファイル書き込み・実 ant は行わない）。
 */
import { planRender } from "./render-ma-agents";
import { AGENT_MANIFESTS } from "../lib/ma/bootstrap-core";

describe("planRender", () => {
  const files = planRender("/tmp/agents");

  test("environment.yaml + 各 agent の agent.yaml/system.md（1 + 2×N ファイル）", () => {
    expect(files).toHaveLength(1 + AGENT_MANIFESTS.length * 2);
    const paths = files.map((f) => f.path);
    expect(paths).toContain("/tmp/agents/environment.yaml");
    for (const m of AGENT_MANIFESTS) {
      expect(paths).toContain(`/tmp/agents/${m.key}.agent.yaml`);
      expect(paths).toContain(`/tmp/agents/${m.key}.system.md`);
    }
  });

  test("各 .agent.yaml は GENERATED ヘッダ + system 参照、.system.md は本文", () => {
    const writerYaml = files.find((f) => f.path.endsWith("x-writer.agent.yaml"))!;
    expect(writerYaml.content).toContain("GENERATED by `npm run ma:render`");
    expect(writerYaml.content).toContain("system: ./x-writer.system.md");

    const writerMd = files.find((f) => f.path.endsWith("x-writer.system.md"))!;
    expect(writerMd.content).toContain("執筆エージェント");
    expect(writerMd.content).not.toContain("GENERATED by"); // md は素のプロンプト本文
  });
});
