/**
 * cost-model-data.ts — cost-model.csv の TS 定数化 (Worker SSOT)
 *
 * Node:fs / readFileSync を使わず、Cloudflare Worker でそのまま import できる。
 * 元 CSV: lib/cost/cost-model.csv (参照用に残置、SSOT はこのファイル)
 */

type Row = {
  category: string;
  runs_per_month: number;
  input_tok_per_run: number;
  output_tok_per_run: number;
  retry_rate: number;
  model: string;
  input_usd_per_mtok: number;
  output_usd_per_mtok: number;
  monthly_jpy_expected: number;
  notes: string;
};

export type CostRow = Row;

export const COST_MODEL_ROWS: CostRow[] = [
  {
    category: "writer",
    runs_per_month: 240,
    input_tok_per_run: 4500,
    output_tok_per_run: 3000,
    retry_rate: 0.30,
    model: "sonnet-4.6",
    input_usd_per_mtok: 3,
    output_usd_per_mtok: 15,
    monthly_jpy_expected: 1840,
    notes: "v10.2 §3.3 30 core × 8 platform、retry 30% で Editor reject。注: P3 で runtime writer は claude-opus-4-8 へ移行。実コストは cost-of の opus-4-8 exact override(5/25) で計上。本行 model/単価(sonnet 3/15) は budget 投影の基準値として据置（cost-of RATE_BY_FAMILY の sonnet 源を opus に汚染しないため数値は変えない）。",
  },
  {
    category: "editor",
    runs_per_month: 312,
    input_tok_per_run: 1500,
    output_tok_per_run: 500,
    retry_rate: 0.05,
    model: "sonnet-4.6",
    input_usd_per_mtok: 3,
    output_usd_per_mtok: 15,
    monthly_jpy_expected: 321,
    notes: "6+4 ルール判定",
  },
  {
    category: "hook_analyzer",
    runs_per_month: 342,
    input_tok_per_run: 800,
    output_tok_per_run: 300,
    retry_rate: 0.05,
    model: "sonnet-4.6",
    input_usd_per_mtok: 3,
    output_usd_per_mtok: 15,
    monthly_jpy_expected: 234,
    notes: "類型分類 + 新候補検出 (Haiku 4.5 でも可)",
  },
  {
    category: "visualizer_prompt",
    runs_per_month: 180,
    input_tok_per_run: 1200,
    output_tok_per_run: 200,
    retry_rate: 0.20,
    model: "sonnet-4.6",
    input_usd_per_mtok: 3,
    output_usd_per_mtok: 15,
    monthly_jpy_expected: 130,
    notes: "画像生成プロンプトのみ (画像本体は別行)",
  },
  {
    category: "interviewer",
    runs_per_month: 60,
    input_tok_per_run: 2000,
    output_tok_per_run: 12000,
    retry_rate: 0.05,
    model: "sonnet-4.6",
    input_usd_per_mtok: 3,
    output_usd_per_mtok: 15,
    monthly_jpy_expected: 1140,
    notes: "月 60 セッション × 8 ターン、cache hit で input は微増",
  },
  {
    category: "optimizer_phase1",
    runs_per_month: 4,
    input_tok_per_run: 30000,
    output_tok_per_run: 5000,
    retry_rate: 0,
    model: "sonnet-4.6",
    input_usd_per_mtok: 3,
    output_usd_per_mtok: 15,
    monthly_jpy_expected: 125,
    notes: "weekly 数値分析",
  },
  {
    category: "optimizer_phase2",
    runs_per_month: 4,
    input_tok_per_run: 50000,
    output_tok_per_run: 12000,
    retry_rate: 0,
    model: "opus-4.7-thinking",
    input_usd_per_mtok: 15,
    output_usd_per_mtok: 75,
    monthly_jpy_expected: 702,
    notes: "weekly 仮説検証 + thinking 5000 tok",
  },
  {
    category: "optimizer_phase3",
    runs_per_month: 4,
    input_tok_per_run: 20000,
    output_tok_per_run: 5000,
    retry_rate: 0,
    model: "sonnet-4.6",
    input_usd_per_mtok: 3,
    output_usd_per_mtok: 15,
    monthly_jpy_expected: 110,
    notes: "weekly 施策立案",
  },
  {
    category: "ma_session_overhead",
    runs_per_month: 72,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "ma",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 84,
    notes: "GA Managed Agents は token 課金（session.usage）。旧 active_seconds 課金は GA に存在しない（teardown.ts と共に撤去済）。本行は session overhead の概算枠として据置、単価 0＝cost-of の RATE_BY_FAMILY 非対象。実トークン費は各工程 model 行（writer/checker=opus/haiku）で計上。",
  },
  {
    category: "image_low",
    runs_per_month: 120,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "gpt-image-2-low",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 153,
    notes: "low 272 tok = $0.00816/枚",
  },
  {
    category: "image_medium",
    runs_per_month: 30,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "gpt-image-2-medium",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 148,
    notes: "medium 1056 tok = $0.03168/枚",
  },
  {
    category: "image_high",
    runs_per_month: 0,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "gpt-image-2-high",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 0,
    notes: "Phase 1 では使用しない",
  },
  {
    category: "x_api_url_post",
    runs_per_month: 30,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "x-pay-per-use",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 936,
    notes: "URL 付き $0.200/req × 30 件 (夕方 17:00 note 送客)",
  },
  {
    category: "x_api_url_none",
    runs_per_month: 120,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "x-pay-per-use",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 281,
    notes: "URL なし $0.015/req × 120 件 (朝昼夕夜)",
  },
  {
    category: "x_api_metrics_read",
    runs_per_month: 150,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "x-pay-per-use",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 70,
    notes: "non_public_metrics read $0.005/req × 150 件",
  },
  {
    category: "twitterapi_io",
    runs_per_month: 80,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "twitterapi-io",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 120,
    notes: "v10.3: 週次定点 24 アカ × 4 週 + 月次新規発掘 5 query。$0.15/1000 tweets × 月 5,300 tweets ≒ ¥120",
  },
  {
    category: "source_ingestion_analysis_monthly",
    runs_per_month: 1,
    input_tok_per_run: 120000,
    output_tok_per_run: 36000,
    retry_rate: 0,
    model: "sonnet-4.6",
    input_usd_per_mtok: 3,
    output_usd_per_mtok: 15,
    monthly_jpy_expected: 140,
    notes: "v10.3: 月次 24 アカ source-ingestion 質的分析。追加カバレッジ拡張時はユーザー承認後に枠変更",
  },
  {
    category: "cloudflare_workers",
    runs_per_month: 1,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "cf-workers-paid",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 780,
    notes: "$5/月 (250 cron + 30s-15min CPU)",
  },
  {
    category: "supabase",
    runs_per_month: 1,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "supabase-free",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 0,
    notes: "Free tier (500MB)、Pro 移行時 +¥3,900",
  },
  {
    category: "line_messaging",
    runs_per_month: 340,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "line-msg-api",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 700,
    notes: "Daily 30 + Weekly 4 + Interview 300 + 異常 6 - 無料 200 = 超過 140 × ¥5",
  },
  {
    category: "x_premium_basic",
    runs_per_month: 1,
    input_tok_per_run: 0,
    output_tok_per_run: 0,
    retry_rate: 0,
    model: "x-premium-basic",
    input_usd_per_mtok: 0,
    output_usd_per_mtok: 0,
    monthly_jpy_expected: 980,
    notes: "X Premium Basic 980 円/月",
  },
];
