import type { StageMeta } from "../types.js";

export const STAGES: StageMeta[] = [
  {
    id: "collect", label: "Collector Agent", group: "ingest",
    purpose: "エージェントが探索的にネタを集め(固定/海外トレンド/キーワード/新ソース/スレ復元)、全件3軸スコア＋理由を付けて materials_store へ全保存。",
    objectiveFunction: "速報性×velocity×ターゲット適合の高いネタの網羅性を最大化（除外は人間UIに委ね、収集網羅性を最大化）",
    inputs: ["twitterapi.io (advanced_search/trends/users/followings/thread)"],
    outputs: ["xad.materials_store (x_inspirations, scores/discovery付き)"],
    keyVariables: [
      { name: "探索スコープ", desc: "固定watchlist＋海外トレンド＋キーワード＋新ソース発見" },
      { name: "scoring weights", desc: "freshness/velocity/target_fit (collector-config)" },
    ],
    logicKind: "llm", sourcePaths: ["apps/x-account-system/lib/ingest/collector.ts"],
    upstream: [], downstream: ["ideation", "compose"],
  },
  {
    id: "buzz-ingest", label: "Buzz Ingest", group: "ingest",
    purpose: "twitterapi.io の seed アカウントから日次 buzz を取得し materials_store へ。",
    objectiveFunction: "一次ソースの網羅性と鮮度を最大化（取りこぼし最小化）",
    inputs: ["twitterapi.io seed accounts"], outputs: ["xad.materials_store (x_inspirations)"],
    keyVariables: [{ name: "seed accounts", desc: "取得対象アカウント群" }],
    logicKind: "io", sourcePaths: ["apps/x-account-system/lib/ingest/"],
    upstream: [], downstream: ["ideation"],
  },
  {
    id: "inspirations-ingest", label: "Inspirations Ingest", group: "ingest",
    purpose: "週次で X/note seeds を取得し materials_store へ。",
    objectiveFunction: "週次インスピレーションの多様性とカバレッジを最大化",
    inputs: ["X seeds", "note seeds"], outputs: ["xad.materials_store"],
    keyVariables: [{ name: "overseas≥6 / domestic≥18 / note≥3", desc: "取得本数下限" }],
    logicKind: "io", sourcePaths: ["apps/x-account-system/lib/ingest/"],
    upstream: [], downstream: ["ideation"],
  },
  {
    id: "compose", label: "Compose (MA writer)", group: "generate",
    purpose: "人間が選抜(queued)した素材から、Managed Agents writer がリサーチ付きで投稿ドラフトを生成する執筆工程。core_idea(inline)+post_drafts(pending) を作成。",
    objectiveFunction: "選抜素材→チャエン層に刺さる投稿ドラフトの質を最大化（数字は素材/web_search で裏取り＝捏造ゼロ）",
    inputs: ["xad.materials_store (selection_status=queued)"],
    outputs: ["xad.core_ideas", "xad.post_drafts (human_approval_status=pending)"],
    keyVariables: [
      { name: "選抜トリガ", desc: "/curation の『執筆へ送る』→ /admin/enqueue?job=compose" },
      { name: "改善レバー", desc: "lib/curation/compose-config.ts(数値) / compose-prompts.ts(判断)" },
    ],
    logicKind: "llm", sourcePaths: ["apps/x-account-system/lib/curation/run-compose.ts", "apps/x-account-system/lib/ma/run-session.ts"],
    upstream: ["collect"], downstream: ["check"],
  },
  {
    id: "check", label: "Check (MA checker)", group: "review",
    purpose: "pending ドラフトを MA チェッカーが重複＋ファクト(web_search で嘘フィルタ)点検。嘘(suspicious)/重複(similar)は差し戻して再生成（上限つき）、不明(unverifiable)/ok は flag を付けて人間 LINE 承認へ。",
    objectiveFunction: "嘘・重複は差し戻し再生成で自動是正し、直らない/不明だけ人間に flag 提示（誇張は許容・出典不要）",
    inputs: ["xad.post_drafts (editor_status=pending, human_approval_status=pending)"],
    outputs: ["xad.post_drafts (approved=人間へ / rejected=差し戻し)", "xad.materials_store (差し戻し時に再 queue: compose_attempts++/last_check_flags)", "LINE 承認依頼(pushApproval)"],
    keyVariables: [
      { name: "差し戻しトリガ", desc: "factcheck=suspicious or duplicate=similar（コード固定＝仕様）" },
      { name: "再生成上限", desc: "check-config.ts maxRedoAttempts(既定2)。到達後は flag+人間へ(flagged_max_retry)＝ループ停止" },
      { name: "起動", desc: "compose→check / check→compose(差し戻し) 自動連鎖 / job=check" },
    ],
    logicKind: "llm", sourcePaths: ["apps/x-account-system/lib/check/run-check.ts", "apps/x-account-system/lib/ma/run-session.ts"],
    upstream: ["compose"], downstream: [],
  },
  {
    id: "ideation", label: "Ideation", group: "ideation",
    purpose: "materials_store から core_ideas を LLM 生成。",
    objectiveFunction: "ターゲット適合 × ネタの多様性を最大化（カテゴリ/フックのバランス）",
    inputs: ["xad.materials_store"], outputs: ["xad.core_ideas"],
    keyVariables: [{ name: "batch limit", desc: "1 回の claim 対象数" }],
    logicKind: "llm", promptRef: "apps/x-account-system/lib/ideation/ideate.ts",
    sourcePaths: ["apps/x-account-system/lib/ideation/ideate.ts"],
    upstream: ["collect", "buzz-ingest", "inspirations-ingest"], downstream: ["writer"],
  },
  {
    id: "writer", label: "Writer", group: "generate",
    purpose: "core_idea から draft 本文を生成。",
    objectiveFunction: "保存・反応につながる訴求力を最大化（チャエン【速報】黄金型への適合）",
    inputs: ["xad.core_ideas"], outputs: ["xad.post_drafts.body"],
    keyVariables: [
      { name: "max_tokens", desc: "format 別" },
      { name: "format", desc: "短文/中尺/長文/スレッド/記事" },
    ],
    logicKind: "llm", promptRef: "apps/x-account-system/lib/writer/writer-x.ts",
    sourcePaths: ["apps/x-account-system/lib/writer/", "apps/x-account-system/src/jobs/post-job.ts"],
    upstream: ["ideation"], downstream: ["hook-classifier"],
  },
  {
    id: "hook-classifier", label: "Hook Classifier", group: "review",
    purpose: "hook を規則ベース(regex/scoring)で分類。LLM ではない。",
    objectiveFunction: "hook 分類の正確性を最大化（誤分類を最小化）",
    inputs: ["draft body"], outputs: ["primary_hook (4分類)"],
    keyVariables: [{ name: "classifyRules", desc: "device/score 規則" }],
    logicKind: "deterministic",
    sourcePaths: ["apps/x-account-system/lib/hook-classifier/classify.ts"],
    upstream: ["writer"], downstream: ["editor"],
  },
  {
    id: "editor", label: "Editor (6+5)", group: "review",
    purpose: "6+5 ルール判定。hard 却下 / soft 警告。LLM judge + factuality judge を含む。",
    objectiveFunction: "公開リスク（業法/DLP/誤報）を最小化しつつ過剰却下を抑える",
    inputs: ["draft body", "materials (出典)"], outputs: ["decision(approved/rejected)", "warnings"],
    keyVariables: [
      { name: "hard rules", desc: "R3/R4/X2/X3/X5(real PII)" },
      { name: "soft rules", desc: "R1/R2/R5/R6/X1/X4/X6 → warnings" },
    ],
    logicKind: "llm", promptRef: "apps/x-account-system/lib/editor/llm-judge.ts",
    sourcePaths: ["apps/x-account-system/lib/editor/pipeline.ts"],
    upstream: ["hook-classifier"], downstream: ["line-approval"],
  },
  {
    id: "line-approval", label: "LINE Approval", group: "approve",
    purpose: "LINE Flex で承認依頼を push し、承認/却下/修正を取り込む。承認は予約待ちストックへ積む。",
    objectiveFunction: "人の承認コストを最小化（軽量・即時の可否判断で誤公開を防ぐ）",
    inputs: ["post_drafts"], outputs: ["承認状態", "予約待ちストック (approved)"],
    keyVariables: [{ name: "LINE_USER_ID", desc: "承認者限定" }],
    logicKind: "io",
    sourcePaths: ["apps/x-account-system/src/jobs/line-event.ts", "apps/x-account-system/src/jobs/post-job.ts"],
    upstream: ["editor"], downstream: ["scheduled-publish"],
  },
  {
    id: "scheduled-publish", label: "Scheduled Publish (chrome-devtools)", group: "publish",
    purpose: "『翌日分を予約して』の turnkey 化: 決定的 slot-planner が承認済みストックをピーク帯へ FIFO 割当→一括バッチ確認(人間ゲート)→chrome-devtools で X 公式予約UIへ順次登録→record で scheduled_for/post_id 記録。source=本人クライアントを保ち X API 直投はしない。",
    objectiveFunction: "ピーク帯への最適割当で到達を最大化（source=本人を維持し誤報リスクは一括バッチ確認の人手で抑制）",
    inputs: ["承認済 post_drafts (human_approval_status='approved' AND scheduled_for IS NULL)"],
    outputs: ["X 予約投稿", "xad.post_drafts.scheduled_for / scheduled_post_id"],
    keyVariables: [
      { name: "trigger", desc: "人のPC起動時『翌日分を予約して』(manual)→plan-scheduled-publish.ts(read-only 提案)" },
      { name: "slot 割当", desc: "決定的 slot-planner.ts: human_approved_at 昇順 FIFO で翌日以降のピーク帯へ" },
      { name: "config レバー", desc: "schedule-config.ts: peakHoursJstWeekday[7,8,12,15,17]/Weekend[8,12,17]/lookaheadDays/maxPerDay (出典 chaen 朝6-8・昼12・夕15-17)" },
      { name: "人間ゲート", desc: "一括バッチ確認: 翌日◯件をこの内容・スロットで予約→人が一度OK→chrome 登録" },
    ],
    logicKind: "io",
    sourcePaths: [
      ".claude/skills/x-scheduled-publish/SKILL.md",
      "apps/x-account-system/lib/publishing/slot-planner.ts",
      "apps/x-account-system/lib/publishing/schedule-config.ts",
      "apps/x-account-system/scripts/plan-scheduled-publish.ts",
      "apps/x-account-system/scripts/record-scheduled-publish.ts",
    ],
    upstream: ["line-approval"], downstream: [],
  },
  {
    id: "safety", label: "Safety (brownout)", group: "review",
    purpose: "handleJob 冒頭の brownout 4段階ゲート。許可外 job を skip する。",
    objectiveFunction: "コスト超過時の被害を最小化（許可 job の段階制御で予算を死守）",
    inputs: ["当月コスト (cost_ledger)"], outputs: ["allowedJobs 判定", "skip"],
    keyVariables: [{ name: "brownout status", desc: "4段階" }],
    logicKind: "deterministic",
    sourcePaths: ["apps/x-account-system/lib/safety/brownout-handler.ts", "apps/x-account-system/src/queue.ts"],
    upstream: [], downstream: [],
  },
  {
    id: "dlp", label: "DLP", group: "review",
    purpose: "editor 内包の PII redact / lint（決定的）。MVP は定義のみ（trace は editor 内）。",
    objectiveFunction: "PII / 顧客機密の漏洩をゼロにする（再現率最優先）",
    inputs: ["draft body"], outputs: ["redacted text", "PII findings"],
    keyVariables: [{ name: "REDACTION_PATTERNS", desc: "PII 検出パターン" }],
    logicKind: "deterministic", sourcePaths: ["apps/x-account-system/lib/dlp/redact.ts"],
    upstream: [], downstream: [],
  },
  {
    id: "optimizer", label: "Optimizer", group: "learn",
    purpose: "Thompson Sampling で 8 パラメータ posterior を更新（optimizer-update cron）。MVP は定義のみ。",
    objectiveFunction: "各パラメータの posterior を更新し長期 reward（エンゲージ/転換）を最大化",
    inputs: ["posts_performance (reward)"], outputs: ["optimizer_state"],
    keyVariables: [{ name: "8 parameters", desc: "段階別 posterior は Phase 2" }],
    logicKind: "deterministic", sourcePaths: ["apps/x-account-system/lib/optimizer/"],
    upstream: [], downstream: [],
  },
];
