import type { StageMeta } from "../types.js";

export const STAGES: StageMeta[] = [
  {
    id: "buzz-ingest", label: "Buzz Ingest", group: "ingest",
    purpose: "twitterapi.io の seed アカウントから日次 buzz を取得し materials_store へ。",
    inputs: ["twitterapi.io seed accounts"], outputs: ["xad.materials_store (x_inspirations)"],
    keyVariables: [{ name: "seed accounts", desc: "取得対象アカウント群" }],
    logicKind: "io", sourcePaths: ["apps/x-account-system/lib/ingest/"],
    upstream: [], downstream: ["ideation"],
  },
  {
    id: "inspirations-ingest", label: "Inspirations Ingest", group: "ingest",
    purpose: "週次で X/note seeds を取得し materials_store へ。",
    inputs: ["X seeds", "note seeds"], outputs: ["xad.materials_store"],
    keyVariables: [{ name: "overseas≥6 / domestic≥18 / note≥3", desc: "取得本数下限" }],
    logicKind: "io", sourcePaths: ["apps/x-account-system/lib/ingest/"],
    upstream: [], downstream: ["ideation"],
  },
  {
    id: "ideation", label: "Ideation", group: "ideation",
    purpose: "materials_store から core_ideas を LLM 生成。",
    inputs: ["xad.materials_store"], outputs: ["xad.core_ideas"],
    keyVariables: [{ name: "batch limit", desc: "1 回の claim 対象数" }],
    logicKind: "llm", promptRef: "apps/x-account-system/lib/ideation/ideate.ts",
    sourcePaths: ["apps/x-account-system/lib/ideation/ideate.ts"],
    upstream: ["buzz-ingest", "inspirations-ingest"], downstream: ["writer"],
  },
  {
    id: "writer", label: "Writer", group: "generate",
    purpose: "core_idea から draft 本文を生成。",
    inputs: ["xad.core_ideas"], outputs: ["xad.post_drafts.body"],
    keyVariables: [
      { name: "max_tokens", desc: "format 別" },
      { name: "format", desc: "短文/中尺/長文/スレッド/記事" },
    ],
    logicKind: "llm", promptRef: "apps/x-account-system/lib/writer/writer-x.ts",
    sourcePaths: ["apps/x-account-system/lib/writer/", "apps/x-account-system/src/jobs/post-job.ts"],
    upstream: ["ideation"], downstream: ["hook-classifier"],
  },
  {
    id: "hook-classifier", label: "Hook Classifier", group: "review",
    purpose: "hook を規則ベース(regex/scoring)で分類。LLM ではない。",
    inputs: ["draft body"], outputs: ["primary_hook (4分類)"],
    keyVariables: [{ name: "classifyRules", desc: "device/score 規則" }],
    logicKind: "deterministic",
    sourcePaths: ["apps/x-account-system/lib/hook-classifier/classify.ts"],
    upstream: ["writer"], downstream: ["editor"],
  },
  {
    id: "editor", label: "Editor (6+5)", group: "review",
    purpose: "6+5 ルール判定。hard 却下 / soft 警告。LLM judge + factuality judge を含む。",
    inputs: ["draft body", "materials (出典)"], outputs: ["decision(approved/rejected)", "warnings"],
    keyVariables: [
      { name: "hard rules", desc: "R3/R4/X2/X3/X5(real PII)" },
      { name: "soft rules", desc: "R1/R2/R5/R6/X1/X4/X6 → warnings" },
    ],
    logicKind: "llm", promptRef: "apps/x-account-system/lib/editor/llm-judge.ts",
    sourcePaths: ["apps/x-account-system/lib/editor/pipeline.ts"],
    upstream: ["hook-classifier"], downstream: ["line-approval"],
  },
  {
    id: "line-approval", label: "LINE Approval", group: "approve",
    purpose: "LINE Flex で承認依頼を push し、承認/却下/修正の応答を取り込む。",
    inputs: ["post_drafts"], outputs: ["承認状態", "publish トリガ"],
    keyVariables: [{ name: "LINE_USER_ID", desc: "承認者限定" }],
    logicKind: "io",
    sourcePaths: ["apps/x-account-system/src/jobs/line-event.ts", "apps/x-account-system/src/jobs/post-job.ts"],
    upstream: ["editor"], downstream: ["publisher"],
  },
  {
    id: "publisher", label: "Publisher (X)", group: "publish",
    purpose: "承認後に X へ投稿。OAuth token 自動 refresh 込み。",
    inputs: ["承認済 post_drafts"], outputs: ["X 投稿", "xad.posts_performance"],
    keyVariables: [{ name: "AUTONOMOUS_PUBLISH", desc: "Phase1=false(承認制)" }],
    logicKind: "io", sourcePaths: ["apps/x-account-system/lib/publisher/"],
    upstream: ["line-approval"], downstream: [],
  },
  {
    id: "safety", label: "Safety (brownout)", group: "review",
    purpose: "handleJob 冒頭の brownout 4段階ゲート。許可外 job を skip する。",
    inputs: ["当月コスト (cost_ledger)"], outputs: ["allowedJobs 判定", "skip"],
    keyVariables: [{ name: "brownout status", desc: "4段階" }],
    logicKind: "deterministic",
    sourcePaths: ["apps/x-account-system/lib/safety/brownout-handler.ts", "apps/x-account-system/src/queue.ts"],
    upstream: [], downstream: [],
  },
  {
    id: "dlp", label: "DLP", group: "review",
    purpose: "editor 内包の PII redact / lint（決定的）。MVP は定義のみ（trace は editor 内）。",
    inputs: ["draft body"], outputs: ["redacted text", "PII findings"],
    keyVariables: [{ name: "REDACTION_PATTERNS", desc: "PII 検出パターン" }],
    logicKind: "deterministic", sourcePaths: ["apps/x-account-system/lib/dlp/redact.ts"],
    upstream: [], downstream: [],
  },
  {
    id: "optimizer", label: "Optimizer", group: "learn",
    purpose: "Thompson Sampling で 8 パラメータ posterior を更新（optimizer-update cron）。MVP は定義のみ。",
    inputs: ["posts_performance (reward)"], outputs: ["optimizer_state"],
    keyVariables: [{ name: "8 parameters", desc: "段階別 posterior は Phase 2" }],
    logicKind: "deterministic", sourcePaths: ["apps/x-account-system/lib/optimizer/"],
    upstream: [], downstream: [],
  },
];
